# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [1]:
import pandas as pd

## imports for Python, Pandas

In [2]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [ ]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [ ]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

In [ ]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [ ]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

In [ ]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [6]:
# assign json file to a variable
json_data = pd.read_json('data/world_bank_projects.json')

# look for keys used for diagnosis
json_data.keys()

Index(['_id', 'approvalfy', 'board_approval_month', 'boardapprovaldate',
       'borrower', 'closingdate', 'country_namecode', 'countrycode',
       'countryname', 'countryshortname', 'docty', 'envassesmentcategorycode',
       'grantamt', 'ibrdcommamt', 'id', 'idacommamt', 'impagency',
       'lendinginstr', 'lendinginstrtype', 'lendprojectcost',
       'majorsector_percent', 'mjsector_namecode', 'mjtheme',
       'mjtheme_namecode', 'mjthemecode', 'prodline', 'prodlinetext',
       'productlinetype', 'project_abstract', 'project_name', 'projectdocs',
       'projectfinancialtype', 'projectstatusdisplay', 'regionname', 'sector',
       'sector1', 'sector2', 'sector3', 'sector4', 'sector_namecode',
       'sectorcode', 'source', 'status', 'supplementprojectflg', 'theme1',
       'theme_namecode', 'themecode', 'totalamt', 'totalcommamt', 'url'],
      dtype='object')

In [7]:
# create DataFrame with columns of only 'countryname' and 'project_name'
country_and_projects = pd.concat([json_data['countryname'], 
                                  json_data['project_name']], 
                                  axis = 1, 
                                  keys = ['countryname','project_name'])

# sort DataFrame by 'countryname' and reset the index
sorted_df = country_and_projects.sort_values('countryname')
sorted_df = sorted_df.reset_index()

# view DataFrame
sorted_df

,index,countryname,project_name
0,46,Africa,RCIP4 - Regional Communications Infrastructure...
1,99,Africa,Additional Financing-West Africa Agricultural ...
2,287,Africa,Agricultural Productivity Program for Southern...
3,51,Africa,"Building Resilience through Innovation, Commun..."
4,184,Africa,Southern Africa Trade and Transport Facilitati...
5,449,Africa,First Part of the Second Phase of the Niger Ba...
6,45,Africa,West Africa Regional Disease Surveillance Cap...
7,65,Africa,Regional Rusumo Falls Hydroelectric Project
8,353,Africa,Nile Cooperation for Results Project
9,58,Africa,Fighting against wildlife poaching and illegal...
10,167,Africa,West Africa Regional Communications Infrastruc...
11,151,Antigua and Barbuda,Public and Social Sector Transformation Projec...
12,101,Arab Republic of Egypt,EG - Helwan South Power Project
13,368,Arab Republic of Egypt,Youth Employment
14,38,Argentine Republic,Adaptation Fund: Increasing Climate Resilience...
15,72,Argentine Republic,Montreal Protocol Hydrochlorofluorocarbons (HC...
16,430,Bosnia and Herzegovina,REAL ESTATE REGISTRATION PROJECT
17,180,Burkina Faso,BF-Youth Employment & Skills Development
18,191,Burkina Faso,Burkina Faso Donsin Transport Infrastructure ...
19,441,Burkina Faso,International Institute for Water and Environm...
20,71,Burkina Faso,Burkina Faso Electricity Sector Support Project
21,310,Burkina Faso,AFSF-Burkina Faso-FCPB
22,274,Burkina Faso,Second Growth and Competitiveness Grant
23,361,Burkina Faso,Sustainable land and forestry management Project
24,360,Burkina Faso,Third Phase Community Based Rural Development ...
25,331,Burkina Faso,Emergency Livestock Feed Access Project
26,366,Central African Republic,Central African Republic - Post Compliance I
27,43,Democratic Republic of Sao Tome and Prin,Sao Tome & Principe-Extractive Industries Tran...
28,159,Democratic Republic of Sao Tome and Prin,Second Governance and Competitiveness Developm...
29,324,Democratic Republic of Timor-Leste,Health Sector Strategic Plan Support Additiona...
...,...,...,...
470,241,The Independent State of Papua New Guine,Multi-Donor Trust Fund for PNG-IBBS
471,489,The Independent State of Papua New Guine,Papua New Guinea Settlement Upgrading Programme
472,312,The Independent State of Papua New Guine,GM- PG Energy Sector Development Project
473,311,The Independent State of Papua New Guine,PNG Energy Sector Development Project
474,2,Tuvalu,Tuvalu Aviation Investment Project - Additiona...
475,363,Ukraine,DEVSTAT Additional Financing
476,47,Ukraine,Ukraine - Smart Grid Project &#8211; PPG
477,468,Ukraine,SECOND ROAD AND SAFETY IMPROVEMENT PROJECT
478,414,Ukraine,CTF in Ukraine
479,48,Union of the Comoros,KM-Electricity Sect. Recovery Proj(FY14)
480,257,Union of the Comoros,Comoros Emergency Response Project (Additional...
481,384,Union of the Comoros,Comoros Development Policy Grant 2
482,487,United Mexican States,Sustainable Production Systems and Biodiversity
483,399,United Mexican States,Sustainable Rural Development Additional Finan...
484,268,United Republic of Tanzania,Energy Sector Capacity Building Project (ESCBP)
485,271,United Republic of Tanzania,TZ First Power and Gas Sector DPO
486,438,United Republic of Tanzania,Tanzania: Third Additional Financing for Agric...
487,31,United Republic of Tanzania,Kihansi Catchment Conservation and Management ...
488,346,United Republic of Tanzania,TANZANIA SECOND CENTRAL TRANSP CORRIDOR PROJEC...
489,432,United Republic of Tanzania,Urban Local Government Strengthening Program
490,437,United Republic of Tanzania,Accelerated Food Security Project Additional F...
491,265,United Republic of Tanzania,Tanzania Poverty Reduction Support Credit 10
492,37,West Bank and Gaza,West Bank and Gaza Cash Transfer Project Addit...
493,389,West Bank and Gaza,GZ-Gaza Water Supply & Sewage System Improvement
494,491,West Bank and Gaza,Water Supply and Sanitation Improvements for W...
495,178,West Bank and Gaza,WBG - PRDP Support V
496,177,West Bank and Gaza,GZ-Second Municipal Development Project
497,69,West Bank and Gaza,GZ-PNGO IV AF
498,55,World,Red Sea and Gulf of Aden Strategic Ecosystem M...
499,238,World,National Human and Animal Health Systems Asses...

In [8]:
# Describe used to check number of non-null values == number of rows in sorted_df 
# Describe also proves all values are unique
sorted_df['project_name'].describe()

count                                 500
unique                                500
top       Ghana Partnership for Education
freq                                    1
Name: project_name, dtype: object

In [9]:
# Count the number of each country value and print top 10 occuring results
unique_country_values = pd.value_counts(sorted_df['countryname'])
print(unique_country_values.head(10))

Republic of Indonesia              19
People's Republic of China         19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
People's Republic of Bangladesh    12
Nepal                              12
Kingdom of Morocco                 12
Africa                             11
Republic of Mozambique             11
Name: countryname, dtype: int64

In [10]:
# Load json file
data = json.load(open('data/world_bank_projects.json'))

# normalize json file to get dictionaries into DataFrame
theme = json_normalize(data, 'mjtheme_namecode')
theme

     code                                          name
0       8                             Human development
1      11
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8
18     10                             Rural development
19      7
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5
1482    6         Social protection and risk management
1483    8
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]

In [11]:
# Empty dictionary to be filled with key=code and value=name
ref_dict = {}

# loop through only unique values of theme['code']
for code in theme['code'].unique():
    
    # Build DataFrame to hold each unique value of theme['code']
    subset_df = theme[theme['code'] == code]
    
    # Use unique code entries as key and add 'name' as value
    ref_dict[code] = subset_df['name'].value_counts().index[0]
print(ref_dict)

{'8': 'Human development', '11': 'Environment and natural resources management', '1': 'Economic management', '6': 'Social protection and risk management', '5': 'Trade and integration', '2': 'Public sector governance', '7': 'Social dev/gender/inclusion', '4': 'Financial and private sector development', '10': 'Rural development', '9': 'Urban development', '3': 'Rule of law'}

In [12]:
# Organize number of times theme used into variable
theme_organized = theme['code'].value_counts()

# Set name of theme for top 10 themes as variable
top_ten_themes_ind = theme_organized[:10].index

# Loop through top ten themes and print out theme name with count of theme used
for i, count in enumerate(theme_organized[:10]):
    print(ref_dict[top_ten_themes_ind[i]], count)

Environment and natural resources management 250
Rural development 216
Human development 210
Public sector governance 199
Social protection and risk management 168
Financial and private sector development 146
Social dev/gender/inclusion 130
Trade and integration 77
Urban development 50
Economic management 38

In [15]:
# Create DataFrame from ref_dict for filling empty theme values
join_dict = pd.DataFrame.from_dict(ref_dict, orient='index')
join_dict

                                               0
8                              Human development
11  Environment and natural resources management
1                            Economic management
6          Social protection and risk management
5                          Trade and integration
2                       Public sector governance
7                    Social dev/gender/inclusion
4       Financial and private sector development
10                             Rural development
9                              Urban development
3                                    Rule of law

In [16]:
# Join join_dict DataFrame and theme DataFrame via the Code index
final_df = join_dict.join(theme.set_index('code'))
final_df

                      0                 name
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management  Economic management
1   Economic management
1   Economic management  Economic management
..                  ...                  ...
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development
9     Urban development    Urban development

[1499 rows x 2 columns]

In [17]:
# Drop the column 'name' that holds empty string values
final_df = final_df.drop('name', axis=1)
final_df

                      0
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
1   Economic management
..                  ...
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development
9     Urban development

[1499 rows x 1 columns]

In [18]:
# Rename column of themes to 'theme'
final_df = final_df.rename(columns= {0: 'theme'})

# Name the index values to 'code'
final_df.index.name = 'code'
final_df.head()

                    theme
code
1     Economic management
1     Economic management
1     Economic management
1     Economic management
1     Economic management